# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . /app

# Create an output directory
RUN mkdir -p /app/output

# Expose the port the app runs on
EXPOSE 8000

# Command to run the app
CMD ["python", "load-models.py"]
